import os
import asyncio
import json
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
from dotenv import load_dotenv
from groq import Groq

load_dotenv()

GROQ_API_KEY = os.getenv('GROQ_API_KEY')
if not GROQ_API_KEY:
    raise RuntimeError('GROQ_API_KEY not set in .env')

client = Groq(api_key=GROQ_API_KEY)
MODEL = 'llama-3.3-70b-versatile'

app = FastAPI(title='ResearchFlow API')
app.add_middleware(CORSMiddleware, allow_origins=['*'], allow_methods=['*'], allow_headers=['*'])

class ResearchRequest(BaseModel):
    topic: str
    email: str | None = None

def llm(system: str, user: str) -> str:
    response = client.chat.completions.create(
        model=MODEL,
        messages=[{'role': 'system', 'content': system}, {'role': 'user', 'content': user}]
    )
    return response.choices[0].message.content

@app.get('/health')
async def health():
    return {'status': 'ok', 'version': '1.0.0'}

@app.post('/research')
async def research(req: ResearchRequest):
    if not req.topic or len(req.topic.strip()) < 3:
        raise HTTPException(status_code=400, detail='Topic must be at least 3 characters.')

    async def stream_pipeline():
        def emit(stage, status, content=''):
            payload = json.dumps({'stage': stage, 'status': status, 'content': content})
            return f'data: {payload}\n\n'

        try:
            yield emit('start', 'running', f'Starting ResearchFlow for: {req.topic}')

            # Agent 1: Planner
            yield emit('Planning', 'running', 'Breaking your topic into research questions...')
            questions = llm(
                'You are a research planning expert. Break the topic into exactly 4 focused sub-questions. Output ONLY a numbered list, nothing else.',
                f'Research topic: {req.topic}'
            )
            yield emit('Planning', 'streaming', questions)

            # Agent 2: Searcher
            yield emit('Searching', 'running', 'Searching and gathering information...')
            findings = llm(
                'You are a web research specialist. For each question, provide detailed findings with facts, data points, and insights. Use your knowledge to answer thoroughly.',
                f'Answer each of these research questions in detail:\n{questions}'
            )
            yield emit('Searching', 'streaming', findings)

            # Agent 3: Synthesizer
            yield emit('Synthesizing', 'running', 'Writing your research report...')
            report = llm(
                '''You are a research analyst. Synthesize findings into a polished report with this structure:
# [Topic] - Research Report
*Generated by ResearchFlow*
## Executive Summary
## Key Findings
## Notable Data Points
## Trends to Watch''',
                f'Topic: {req.topic}\n\nFindings:\n{findings}'
            )
            yield emit('Synthesizing', 'streaming', report)

            # Agent 4: Delivery
            yield emit('Delivering', 'running', 'Preparing your email report...')
            email_content = llm(
                'Format this research report as a professional email with a clear subject line.',
                f'Format this as an email:\n{report}'
            )
            yield emit('Delivering', 'streaming', email_content)

            yield emit('complete', 'done', report)

        except Exception as e:
            yield emit('error', 'failed', str(e))

    return StreamingResponse(
        stream_pipeline(),
        media_type='text/event-stream',
        headers={'Cache-Control': 'no-cache', 'X-Accel-Buffering': 'no'},
    )

if __name__ == '__main__':
    import uvicorn
    uvicorn.run('app:app', host='0.0.0.0', port=8000, reload=True)
