from google.adk.agents import LlmAgent

DELIVERY_PROMPT = '''You are a delivery specialist. You will receive a research report in markdown format.

Your job is to format it as a professional email ready to send.

Output format:

SUBJECT: [Specific subject line about the research topic]

BODY:
Hi,

Here is your ResearchFlow research report:

[Full report content, converted from markdown to clean plain text]

---
This report was automatically generated by ResearchFlow, a multi-agent AI research assistant.
Research powered by Google Search + Gemini.

Best regards,
ResearchFlow

Rules:
- Convert markdown headers to plain text with blank lines
- Keep bullet points as-is
- Subject line should mention the specific topic researched
'''

delivery_agent = LlmAgent(
    name='delivery_agent',
    model='gemini-2.0-flash-lite',
    description='Formats the research report as an email and prepares it for delivery.',
    instruction=DELIVERY_PROMPT,
)
